spring:
  application:
    name: learning_management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lms_management_db?createDatabaseIfNotExist=true
    username: root
    password: coditas
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

app:
  jwt:
    secret: "bXkgbmFtZSBpcyBhYmlkIGFuZCBpIGFtIG1ha2luZyBqYXZhIHByb2plY3Q="
    access-token-expiration: 900000
    refreh-token-expiration: 604800000